---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: k-api
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^master-(?P<ts>[0-9]{10})-.*
  imageRepositoryRef:
    name: k-api
  policy:
    numerical:
      order: desc
