---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: k-api
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^master-.*
  imageRepositoryRef:
    name: k-api
  policy:
    alphabetical:
      order: desc
